"""add quantity to rooms

Revision ID: eb82a7dd1fec
Revises: 8472256db299
Create Date: 2026-05-22 19:43:32.039318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb82a7dd1fec"
down_revision: Union[str, Sequence[str], None] = "8472256db299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("quantity", sa.Integer(), nullable=False))
    op.drop_column("rooms", "quanlity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("quanlity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("rooms", "quantity")
    # ### end Alembic commands ###
